//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 05:50:05 PM GMT 
//

package ie.gmit.sw.Model2;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cust_firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cust_lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cust_mobile" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cust_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cust_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "custID", "custFirstName", "custLastName", "custMobile", "custAddress", "custEmail" })
@XmlRootElement(name = "Customer")
public class Customer implements Serializable {

	private static final long serialVersionUID = 1L;
	protected int custID;
	@XmlElement(name = "custFirstName", required = true)
	protected String custFirstName;
	@XmlElement(name = "custLastName", required = true)
	protected String custLastName;
	@XmlElement(name = "custMobile")
	protected int custMobile;
	@XmlElement(name = "custAddress", required = true)
	protected String custAddress;
	@XmlElement(name = "custEmail", required = true)
	protected String custEmail;

	public Customer() {
		super();
	}

	public Customer(int custID, String custFirstName, String custLastName, int custMobile, String custAddress,
			String custEmail) {
		super();
		this.custID = custID;
		this.custFirstName = custFirstName;
		this.custLastName = custLastName;
		this.custMobile = custMobile;
		this.custAddress = custAddress;
		this.custEmail = custEmail;
	}

	/**
	 * Gets the value of the custID property.
	 * 
	 */
	public int getCustID() {
		return custID;
	}

	/**
	 * Sets the value of the custID property.
	 * 
	 */
	public void setCustID(int value) {
		this.custID = value;
	}

	/**
	 * Gets the value of the custFirstName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustFirstName() {
		return custFirstName;
	}

	/**
	 * Sets the value of the custFirstName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustFirstName(String value) {
		this.custFirstName = value;
	}

	/**
	 * Gets the value of the custLastName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustLastName() {
		return custLastName;
	}

	/**
	 * Sets the value of the custLastName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustLastName(String value) {
		this.custLastName = value;
	}

	/**
	 * Gets the value of the custMobile property.
	 * 
	 */
	public int getCustMobile() {
		return custMobile;
	}

	/**
	 * Sets the value of the custMobile property.
	 * 
	 */
	public void setCustMobile(int value) {
		this.custMobile = value;
	}

	/**
	 * Gets the value of the custAddress property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustAddress() {
		return custAddress;
	}

	/**
	 * Sets the value of the custAddress property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustAddress(String value) {
		this.custAddress = value;
	}

	/**
	 * Gets the value of the custEmail property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustEmail() {
		return custEmail;
	}

	/**
	 * Sets the value of the custEmail property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustEmail(String value) {
		this.custEmail = value;
	}

}
